apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Universal CI - ${{ env.APP_NAME }}
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
env:
  APP_NAME: reef-asia
  LANGUAGE: go
  COVERAGE_ROOT: src
  DEBUG: "true"

jobs:
  test:
    uses: github.com/cb-squidstack/cb-squidstack/.cloudbees/workflows/test-generic.yaml@main
    with:
      app_name: reef-asia
      language: go
      coverage_root: src
      debug: "true"
      enable_smart_tests: "true"
    secrets: inherit
    vars: inherit

  build:
    uses: github.com/cb-squidstack/cb-squidstack/.cloudbees/workflows/build-generic.yaml@main
    with:
      app_name: reef-asia
      docker_user: ${{ vars.DOCKER_USER }}
      commit_sha: ${{ cloudbees.scm.sha }}
      push_latest: "true"
    secrets:
      docker_token: ${{ secrets.DOCKER_TOKEN }}
    vars: inherit

  deployDev:
    if: ${{ cloudbees.scm.branch != 'main' }}
    environment: squid-dev
    uses: github.com/cb-squidstack/cb-squidstack/.cloudbees/workflows/deploy-generic.yaml@main
    needs: [test, build]
    with:
      environment_name: squid-dev
      component_name: reef-asia
      docker_repo: ${{ vars.DOCKER_USER }}/reef-asia
      uses_postgres: "false"
      uses_liquibase: "false"
      artifact_id: ${{ needs.build.outputs.PRIMARY_ARTIFACT_ID }}
      version: ${{ needs.build.outputs.VERSION }}
      commit_sha: ${{ cloudbees.scm.sha }}
      feature_flags_enabled: "true"
    secrets: inherit
    vars: inherit

  deployPreProd:
    if: ${{ cloudbees.scm.branch == 'main' }}
    environment: squid-preprod
    uses: github.com/cb-squidstack/cb-squidstack/.cloudbees/workflows/deploy-generic.yaml@main
    needs: [test, build]
    with:
      environment_name: squid-preprod
      component_name: reef-asia
      docker_repo: ${{ vars.DOCKER_USER }}/reef-asia
      uses_postgres: "false"
      uses_liquibase: "false"
      artifact_id: ${{ needs.build.outputs.PRIMARY_ARTIFACT_ID }}
      version: ${{ needs.build.outputs.VERSION }}
      commit_sha: ${{ cloudbees.scm.sha }}
      feature_flags_enabled: "true"
    secrets: inherit
    vars: inherit

  deployProd:
    if: ${{ cloudbees.scm.branch == 'main' }}
    environment: squid-prod
    uses: github.com/cb-squidstack/cb-squidstack/.cloudbees/workflows/deploy-generic.yaml@main
    needs: [test, build, deployPreProd]
    with:
      environment_name: squid-prod
      component_name: reef-asia
      docker_repo: ${{ vars.DOCKER_USER }}/reef-asia
      uses_postgres: "false"
      uses_liquibase: "false"
      artifact_id: ${{ needs.build.outputs.PRIMARY_ARTIFACT_ID }}
      version: ${{ needs.build.outputs.VERSION }}
      commit_sha: ${{ cloudbees.scm.sha }}
      feature_flags_enabled: "true"
    secrets: inherit
    vars: inherit

  triggerRelease:
    if: false  # Disabled to avoid Unify rate limits - change to 'cloudbees.scm.branch == main' to enable
    needs: [test, build, deployPreProd]
    uses: github.com/cb-squidstack/cb-squidstack/.cloudbees/workflows/release-generic.yaml@main
    with:
      component_name: reef-asia
      component_id: "a8758da1-9e8b-47d6-98fd-68b94e71f063"
      version: ${{ needs.build.outputs.VERSION }}
      smart_tests_build_name: ${{ needs.test.outputs.SMART_TESTS_BUILD_NAME }}
      environment: squid-demo-3
      release_name_prefix: "reef-asia"
    secrets: inherit
    vars: inherit
